[package]
name = "person-bridge"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = "0.4"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
name = "person_bridge_rs"
crate-type = ["staticlib"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
